test_robot:
  wheels_controller:
    type: "position_controllers/JointGroupPositionController"
    joints:
      - j1
      - j2
    gains:
      j1: { p: 100.0, i: 0.01, d: 10, i_clamp: 0.0 }
      j2: { p: 100.0, i: 0.01, d: 10, i_clamp: 0.0 }
